---
- name: install httpd package
  yum: name=httpd state=latest

- name: copy vip and kernel conf
  template: src=setka.sh dest=~/setka.sh

- name: exec setka.sh
  shell: sh ~/setka.sh start

- name: install condiguration file for httpd
  template: src=httpd2.4.conf.j2 dest=/etc/httpd/conf/httpd.conf
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  notify:
  - restart httpd

- name: install condiguration file for httpd
  template: src=httpd2.2.conf.j2 dest=/etc/httpd/conf/httpd.conf
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  notify:
  - restart httpd

- name: test page of index.html
  shell: echo "<h1>The page from {{ WEB }}</h1>" > /var/www/html/index.html

- name: start httpd service
  service: enabled=true name=httpd state=started
