---
- name: Create zabbix directory
  file: path=/opt/zabbix state=directory
- name: Copy zabbix rpm and scripts
  copy: src={{item}} dest=/opt/zabbix
  with_items:
    - zabbix-2.4.5-1.el6.x86_64.rpm
    - zabbix-agent-2.4.5-1.el6.x86_64.rpm
    - zabbix-sender-2.4.5-1.el6.x86_64.rpm

- name: Install zabbix agent
  yum: name=/opt/zabbix/{{item}} state=present
  with_items:
    - zabbix-2.4.5-1.el6.x86_64.rpm
    - zabbix-agent-2.4.5-1.el6.x86_64.rpm
    - zabbix-sender-2.4.5-1.el6.x86_64.rpm

- name: Zabbix config file
  template: src=zabbix_agentd_conf.ja2 dest=/etc/zabbix/zabbix_agentd.conf
  notify:
    - Restart zabbix agent
  
- name: Start Zabbix agent
  service: name=zabbix-agent state=started enabled=yes
