---
- name: install denpendency package
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - pcre
    - openssl
    - pcre-devel
    - openssl-devel
    - zlib-devel
    - gd
    - gd-devel

- name: create nginx pid user
  user: name={{ nginxuser }} system=yes shell=/sbin/nologin createhome=no

- name: download nginx source
  get_url:
    url: "http://nginx.org/download/nginx-{{ ngxversion }}.tar.gz"
    dest: "{{ srcpath }}/nginx-{{ ngxversion }}.tar.gz"
    checksum: md5:204a20cb4f0b0c9db746c630d89ff4ea

- name: unarchive nginx.tar.gz
  command: >
    tar -C {{ srcpath }}  -xvf {{ srcpath }}/{{ nginxtar }}

- name: compile and install nginx
  shell: > 
    cd {{ srcpath }}/{{ nginxtar | replace('.tar.gz','')}} && \
    ./configure --prefix={{ nginxpath }} \
    --user={{ nginxuser }} \
    --group={{ nginxgroup }} \
    --sbin-path={{ nginxpath }}/sbin/nginx \
    --conf-path={{ ngxconf }}/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/var/run/nginx/nginx.pid  \
    --lock-path=/var/lock/nginx.lock \
    --with-http_ssl_module \
    --with-http_flv_module \
    --with-http_stub_status_module \
    --with-http_gzip_static_module \
    --http-client-body-temp-path=/var/tmp/nginx/client/ \
    --http-proxy-temp-path=/var/tmp/nginx/proxy/ \
    --http-fastcgi-temp-path=/var/tmp/nginx/fcgi/ \
    --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi \
    --http-scgi-temp-path=/var/tmp/nginx/scgi \
    --with-pcre && \
    make -j `lscpu | awk '$1~/^CPU\(s\):/{print $2}'` && \
    make install
  args:
    creates: "{{ nginxpath }}"

- name: copy nginx conf
  template: src=nginx.conf.j2 dest={{ ngxconf }}/nginx.conf

- name: create client path and input env
  shell: >
    mkdir -pv /var/tmp/nginx/client && \
    echo "export PATH={{ nginxpath }}/sbin:$PATH" >/etc/profile.d/nginx.sh && \
    source /etc/profile

- name: copy nginx init script
  template: src=nginx.init dest=/etc/init.d/nginx mode=0755
#  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  notify: start nginx service
